const fs = require('fs');
const path = require('path');
let code = fs.readFileSync('scratch/run_validation_batch3.ts', 'utf8');
code = code.replace(/validation_corpus_batch3\.cpp/g, 'validation_corpus_batch4.cpp');
code = code.replace(/validation_answers_batch3\.txt/g, 'validation_answers_batch4.txt');
code = code.replace(/validation_results_batch3_final\.txt/g, 'validation_results_batch4.txt');
code = code.replace(/validation_results_batch3\.txt/g, 'validation_results_batch4.txt');
code = code.replace(/__dirname \+ '\/validation_corpus_batch4\.cpp'/g, 'path.join(__dirname, "..", "validation_corpus_batch4.cpp")');
code = code.replace(/__dirname \+ '\/validation_answers_batch4\.txt'/g, 'path.join(__dirname, "..", "validation_answers_batch4.txt")');
code = code.replace(/__dirname \+ '\/validation_results_batch4\.txt'/g, 'path.join(__dirname, "..", "validation_results_batch4.txt")');
fs.writeFileSync('scratch/run_validation_batch4.ts', code);
console.log('Script recreated successfully.');
